#Makefile for rlogviewd

#comment this on non cygwin systems if you wish to use the strip rule
LAMEXT = .exe

EXE = rlogviewd

CC = gcc
CFLAGS = -O2

all : $(EXE)

$(ExE) :
	$(CC) $(CFLAGS) $(EXE).c -o $(EXE)

strip : all
	strip $(EXE)$(LAMEXT)
